/**
 * Legacy Report — A4 Disclosure text (source: "A4 Disclosure.pdf").
 *
 * The disclosure is static legal/marketing boilerplate reproduced verbatim from source. It is
 * long, so it is rendered across two sheets (see LegacyDisclosurePageA/B); DISCLOSURE_SPLIT is
 * the paragraph index where page one ends and page two begins.
 */
export const DISCLOSURE_PARAGRAPHS: string[] = [
	'This model presents the structure and operation of a nonqualified supplemental executive retirement plan ("SERP") specifically designed for the entity identified. There is considerable flexibility in designing these plans, so it is important that the objectives be clearly set forth and that the employer satisfy itself that the plan it adopts is designed to meet these objectives. In addition, the design and success of the plan will depend on the assumptions and employee census data utilized, so it is important that the employer review this data and assumptions to make sure that they are accurate and realistic.',
	'The after tax costs shown in this model do not reflect any federal corporate Alternative Minimum Tax (AMT) which may be due. Because particular facts and circumstances may vary, you must consult your tax advisor regarding all questions concerning the tax implications of life insurance policies and supplemental plans.',
	'The financial effects presented in this model depend significantly on the expected tax treatment of individual life insurance policies. This presentation represents our understanding of the application of federal income tax laws but should not be construed as tax or legal advice. The parties must place their reliance upon the advice of their own tax and legal advisors for the actual results which may be obtained.',
	'An executive owes taxes on plan benefits upon receipt of the benefit payments if the employer is a for profit entity, but upon vesting for a not-for-profit employer. If an executives dies, plan benefits may be subject to estate taxes. Because particular facts and circumstances may vary, executives should consult their tax and legal advisors for the tax implications of this plan.',
	'The Employee Retirement Income Security Act of 1974 (ERISA) and federal and state securities laws may impose regulatory requirements on the plan presented herein. In addition, a number of written agreements may need to be prepared and executed in connection with the plan. Employers and employees must consult their own legal and tax advisors regarding the plan provisions. A securities registration may be advisable in certain cases.',
	"This presentation demonstrates how a life insurance policy can operate within an executive benefit plan to provide advantages to both employers and executives. Material may be presented on both a composite and individual executive basis. Composite insurance values are combined individual values. Please note that insurance values are hypothetical; values shown are not guaranteed. Insurance values are highly sensitive to the assumptions and may show different results if these assumptions are changed or not met. The model is based on hypothetical pricing reflecting products available in the marketplace rather than any specific carrier's policy. The model presents current charges and hypothetical investment returns for variable universal life policies. For variable universal life, any hypotheticals used are not meant to project or predict investment results as such forecasts are strictly prohibited by FINRA rules. The purpose of any hypothetical return is to show how the performance of the underlying investment accounts could affect the policy cash value and death benefit.",
	"The cost of insurance of a variable universal life policy may be paid in cash or by internal policy values. A variable policy's cash value, cash surrender value and, in some cases, death benefits will vary, since the values of the investment divisions of the separate accounts are not guaranteed and will fluctuate based on market conditions. These fluctuations may result in insufficient funds being available to implement your stated objectives. A policy's cash value and death benefit will be reduced by any policy loans and withdrawals. If the loan is on a variable universal life policy, the borrowed funds will not participate in the investment performance of the separate accounts, although they will be credited with a fixed rate of interest. A policy may lapse due to insufficient premium and/or poor performance. Loans or withdrawals may cause a policy to lapse. Adverse tax consequences could result if a policy with outstanding loans endows or is surrendered or is permitted to lapse. The same is true if the insurer charges more than the charges and expenses that are reflected in this model, as the insurer is permitted to charge up to the maximum charges and expenses that are stated in the policy. In either case, lower earnings and/or higher charges and expenses may cause lower cash value accumulations than originally illustrated. These lower cash values may prevent the policy from achieving its objectives, and may cause the policy to lapse. It is emphasized that the results in this model are hypothetical only and should not be deemed a representation of a particular policy or future results. The insurance values are neither estimates nor guarantees of future performance.",
	'When you purchase a specific VUL product, you will receive a product and fund prospectus for that product. Investors are asked to consider the investment objectives, risks and charges and expenses of the investment carefully before investing. Both the product and fund prospectuses contain this and other information about the product and underlying investment options. Please read the prospectuses carefully before investing.'
];

/** Page one renders paragraphs [0, DISCLOSURE_SPLIT); page two renders the remainder. */
export const DISCLOSURE_SPLIT = 5;
